services:
    senky.massnotification.listener:
        class: senky\massnotification\event\listener
        arguments:
            - '@request'
        tags:
            - { name: event.listener }

    senky.massnotification.notification.type.manual:
        class: senky\massnotification\notification\type\manual
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_dispatcher, ['@dispatcher']]
            - [set_user_loader, ['@user_loader']]
        tags:
            - { name: notification.type }
